# Generated by Django 4.0.6 on 2022-11-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
